import Head from 'next/head'
import { useRouter } from 'next/router'
import { useEffect, useState } from 'react'

import styles from '../../styles/modules/Product.module.css'

import { MongoClient } from 'mongodb'

import { Header } from '../../src/components/Header/Header'
import { NavBack } from '../../src/components/NavBack'
import { ProductOvView } from '../../src/components/Product/ProductOvView'
import { ProductContent } from '../../src/components/Product/ProductContent'
import { ProductGallery } from '../../src/components/Product/ProductGallery'
import { Recommend } from '../../src/components/Product/Recommend'
import { Menu } from '../../src/components/Menu/Menu'
import { About } from '../../src/components/About'
import { Footer } from '../../src/components/Footer/Footer'

import { Overlay } from '../../src/components/Overlay'
import { useAppContext } from '../../src/context/appContext'

export default function Product({ data }) {
  const [isCartUpdate, setIsCartUpdate] = useState(false)

  let { cart } = useAppContext()

  let renderCart = () => {
    setIsCartUpdate(!isCartUpdate)
  }

  const router = useRouter()
  const { category, slug } = router.query

  let product = data.find((product) => product.slug == slug)

  return (
    <div className={styles.page}>
      <Head>
        <title>{product.name} | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header className={styles.pageHeader}>
        <Header isCartUpdate={isCartUpdate} renderCart={renderCart} />
      </header>

      <main className={`${styles.pageMain} ${styles.main}`}>
        <section className={styles.mainNavBack}>
          <NavBack />
        </section>

        <section className={styles.mainProdOvView}>
          <ProductOvView product={product} renderCart={renderCart} />
        </section>
        <section className={styles.mainProdContent}>
          <ProductContent
            features={product.features}
            includes={product.includes}
          />
        </section>
        <section className={styles.mainProdGallery}>
          <ProductGallery gallery={product.gallery} />
        </section>

        <section className={styles.mainRecommend}>
          <Recommend recommend={product.others} />
        </section>
        <section className={styles.mainMenu}>
          <Menu />
        </section>
        <section className={styles.mainAbout}>
          <About />
        </section>
      </main>

      <footer className={styles.pageFooter}>
        <Footer />
      </footer>
    </div>
  )
}

export const getServerSideProps = async () => {
  const client = await MongoClient.connect(process.env.MONGODB_URI)

  const db = client.db('audiophile')

  const yourCollection = db.collection('product')

  let cursor = await yourCollection.find()
  let data = []

  await cursor.forEach((entry) => {
    entry._id = entry._id.toString()
    data.push(entry)
  })

  cursor.close()

  return {
    props: {
      data,
    },
  }
}
