import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'

import {Footer} from '../src/components/Footer'
import {Menu} from '../src/components/Menu'

export default function Home() {
  return (
    <div className={"page"}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
	<link rel="preconnect" href="https://fonts.googleapis.com" />
	<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
	<link href="https://fonts.googleapis.com/css2?family=Manrope:wght@400;500;700&display=swap" rel="stylesheet" /> 
     </Head>
      <Menu className="page__menu" />
      <Footer className="page__footer" />

    </div>
  )
}
