import { useEffect, useState } from 'react'
import Head from 'next/head'
import dynamic from 'next/dynamic'

import styles from '../styles/modules/Home.module.css'

import { Header } from '../src/components/Header/Header'
import { Hero } from '../src/components/Home/Hero'
import { Menu } from '../src/components/Menu/Menu'
import { FeatureProductA } from '../src/components/Home/FeatureProductA'
import { FeatureProductB } from '../src/components/Home/FeatureProductB'
import { FeatureProductC } from '../src/components/Home/FeatureProductC'
import { About } from '../src/components/About'
import { Footer } from '../src/components/Footer/Footer'

import { useAppContext } from '../src/context/appContext'

import { ChatIcon } from '../src/components/Ably/ChatIcon'
const AblyChatComponent = dynamic(() => import('../src/components/Ably/AblyChatComponent'), { ssr: false });

export default function Home({ countryList }) {
  let { setCountries } = useAppContext()

    const [isOpenChat, setIsOpenChat] = useState(false)

    let toggleChat = () => {
        setIsOpenChat(!isOpenChat)
    }

  useEffect(() => {
    setCountries(countryList)
  }, [])

  return (
      <div className={isOpenChat ? styles.chatPage : styles.page}>
      <Head>
        <title>Home | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      { isOpenChat
     ? <>
         <header></header>
         <main style={{marginTop: '32px'}}>
        <div>
          <AblyChatComponent toggleChat={toggleChat}/>
        </div>

         </main>
         <footer></footer>
       </>
      
        :
        <>
      <header className={styles.pageHeader}>
        <Header />
      </header>

        <main className={`${styles.pageMain} ${styles.main}`}>
        <section className={`${styles.mainHero}`}>
          <Hero />
        </section>

        <section className={`${styles.mainProductNav}`}>
          <Menu />
        </section>

        <section className={`${styles.mainFtProd} ${styles.ftProd}`}>
          <div className={`${styles.ftProdA}`}>
            <FeatureProductA />
          </div>
          <div className={`${styles.ftProdB}`}>
            <FeatureProductB />
          </div>
          <div className={`${styles.ftProdC}`}>
            <FeatureProductC />
          </div>
        </section>

          <section
            className={`${styles.mainChat}`}
            onClick={toggleChat}
          >

            <ChatIcon />
          </section>


        <section className={styles.mainAbout}>
          <About />
        </section>
      </main>

      <footer className={styles.pageFooter}>
        <Footer />
      </footer>
        </> }
    </div>
  )
}

export async function getStaticProps() {
  const fs = require('fs/promises')
  const fileName = 'public/assets/static/data.csv'

  const readFile = async (fileName) => {
    try {
      const data = await fs.readFile(fileName, 'utf8')
      let array = await data.split('\r')
      await array.shift()
      let countries = await array.map((country) => country.slice(1))

      return countries
    } catch (err) {
      console.log(err)
    }
  }

  let countryList = await readFile(fileName)

  return {
    props: {
      countryList,
    },
  }
}
