import Head from 'next/head';
import styles from '../styles/modules/Product.module.css';
import { ShippingForm } from '../src/components/ShippingForm';

export default function Mock({ data }) {
  return (
    <div className={""}>
      <Head>
        <title>Home | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ShippingForm />
    </div>
  )
}
