import { useEffect } from 'react'
import Head from 'next/head'

//import styles from '../styles/modules/Home.module.css'
//import Deck from '../src/components/Success/Deck';
//import MapNew from '../src/components/Success/MapNew';
import Example2 from '../src/components/Success/Example2';

// import { Header } from '../src/components/Header/Header'
// import { Hero } from '../src/components/Home/Hero'
// import { Menu } from '../src/components/Menu/Menu'
// import { FeatureProductA } from '../src/components/Home/FeatureProductA'
// import { FeatureProductB } from '../src/components/Home/FeatureProductB'
// import { FeatureProductC } from '../src/components/Home/FeatureProductC'
// import { About } from '../src/components/About'
// import { Footer } from '../src/components/Footer/Footer'

// import { useAppContext } from '../src/context/appContext'

export default function Playground({ countryList }) {

  return (
    <div >
      <Head>
        <title>Home | Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <header >
      </header>

      <main style={{
          /* width: '100%', */
          /* height: '100%', */
          /* display: 'flex', */
          /* justifyContent: 'center', */
          /* alignItems: 'center', */
          /* position: 'relative', */
          /* right: '25vw', */
          /* top: '25vh', */
      }}>
        <Example2 />
        {/* <Deck/> */}
        {/* <MapNew /> */}
      </main>

      <footer >
      </footer>
    </div>
  )
}

